### ISSUE TITLE
FR: alternative for libusb's `libusb_detach_kernel_driver` et. al.

### ISSUE THREAD

**Issue by bugadani** [kevinmehall/nusb#34]
`probe-rs` now uses `nusb` instead of `libftdi1-sys`/`libusb` to implement its FTDI probe support. It works pretty well, but unfortunately on Linux users need to manually remove the `ftdi_sio` kernel module each time they connect a FTDI device, otherwise the device reports busy and nusb can't claim its interfaces.

`libftdi` calls [libusb_detach_kernel_driver](https://github.com/particle-iot/libftdi/blob/master/src/ftdi.c#L621) which then uses [ioctl](https://github.com/libusb/libusb/blob/0929a2b1d19c4297b10a5c5f52fee8b4e052f2ee/libusb/os/linux_usbfs.c#L1741) to detach the kernel drivers temporarily. What do you think, could we a) introduce this mechanism into `nusb`, or could we at least add some way to work with a particular device's file descriptor?

**Comment by kevinmehall** [comment]
Yes, this would be good to add. There's a [ioctl `USBDEVFS_DISCONNECT_CLAIM`](https://github.com/torvalds/linux/commit/0837e7e5270bd5547ba5763f11611dc43f677b3d) provides a race-free way to both detach a driver and claim the interface that libusb uses with`libusb_set_auto_detach_kernel_driver`, which seems like the better API than the standalone `libusb_detach_kernel_driver`. Maybe a Linux-only `Device::detach_and_claim_interface()` that works like `claim_interface` but uses that ioctl.

Not sure if it's worth exposing the functionality to restrict which kernel driver is detached, but it should probably default to `USBDEVFS_DISCONNECT_CLAIM_EXCEPT_DRIVER` `usbfs` to avoid detaching another app using nusb or libusb.
