### ISSUE TITLE
Thread-safety and cancel-safety

### ISSUE THREAD

**Issue by axelkar** [kevinmehall/nusb#60]
Are the methods safe to use across threads and are they [safe to cancel](https://docs.rs/tokio/latest/tokio/macro.select.html#cancellation-safety)?

**Comment by kevinmehall** [comment]
Thread safety is a given in safe Rust. Most types are Send + Sync and can be used across threads.

[TransferFuture](https://docs.rs/nusb/latest/nusb/transfer/struct.TransferFuture.html) is not cancel safe and documents this caveat. Use the [Queue API](https://docs.rs/nusb/latest/nusb/transfer/struct.Queue.html), whose `next_complete` is cancel-safe.
