### ISSUE TITLE
`Queue::submit`, what is the limit on number of transfers?

### ISSUE THREAD

**Issue by korken89** [kevinmehall/nusb#93]
Hi!

The documentation of `Queue::submit` is not clear on its limitations, and if one ships e.g. 1M transfers it silently fails.
What are the limitations really? I can fix a PR documenting it.

Thanks for the insight!

**Comment by kevinmehall** [comment]
On Linux there is a global limit `/sys/module/usbcore/parameters/usbfs_memory_mb` (default 16mb) for the total size of all in-flight transfers across all devices and all processes.

I do not know of documented limits for Windows and macOS, nor have I tested pushing the limits. If you find documentation or run tests, please let me know.

Windows does expose a API to get a [MAXIMUM_TRANSFER_SIZE](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-functions-for-pipe-policy-modification) per transfer that we should probably wrap and expose. It is normally 2MB.

**Comment by korken89** [comment]
I dug for a bit but quickly realized I'm in over my head and can unfortunately not spend more time here.
Thank you for the insight!
