### ISSUE TITLE
wire receive error but sending works

### ISSUE THREAD

**Issue by ple1n** [kevinmehall/nusb#94]
![image](https://github.com/user-attachments/assets/535ca9f1-932e-46f5-ace3-83c55ad2031e)

https://github.com/jamesmunns/postcard-rpc/issues/62#issuecomment-2504158367

@kevinmehall

**Comment by kevinmehall** [comment]
Turned out not to be an issue with nusb, but nusb could definitely provide a better error message when the endpoint address is wrong. Planned 0.2 API redesign requires getting an endpoint object before submitting a transfer so provides an opportunity to do so.
